# Generated by Django 5.0.2 on 2024-04-17 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_reservation_car_reservation_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='car_image/default_car_icon.png', null=True, upload_to='car_image'),
        ),
        migrations.AlterField(
            model_name='employeeaccount',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.car'),
        ),
    ]
