# Generated by Django 5.0.2 on 2024-04-18 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_car_image_alter_employeeaccount_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentallocation',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='rentallocation',
            name='car',
        ),
        migrations.RemoveField(
            model_name='rentallocation',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeeaccount',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.rentallocation'),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='frontend.rentallocation'),
        ),
    ]
